import os
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_HOSTNAME = "192.168.1.6"
POSTGRES_PORT = 5432
DISCORD_BOT_TOKEN = os.environ['DISCORD_BOT_TOKEN']
OSU_CLIENT_ID = os.environ['OSU_CLIENT_ID']
OSU_API_KEY = os.environ['OSU_API_KEY']
BASE_PATH = "/data"