import os
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_HOSTNAME = "172.18.0.1"
POSTGRES_PORT = 5432
DISCORD_BOT_TOKEN = os.environ['DISCORD_BOT_TOKEN']
DISCORD_LOGGING_WEBHOOK = os.environ['DISCORD_LOGGING_WEBHOOK']
OSU_CLIENT_ID = os.environ['OSU_CLIENT_ID']
OSU_API_KEY = os.environ['OSU_API_KEY']
BASE_PATH = "/data"